server:
  port: 8989
  servlet:
    context-path: /uploadfile
spring:
  redis:
    host: 124.221.243.242
    port: 6379
  datasource:
    url: jdbc:mysql://124.221.243.242/rytlockbrimstone?serverTimezone=UTC
    #    url: jdbc:mysql://localhost/voika?serverTimezone=UTC
    #    url: jdbc:mysql://10.211.55.3/voika?serverTimezone=UTC
    #    username: voika
    username: rytlock
    password: 3865571999@Ghy
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: auth-service
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
my-config:
  jwt:
    secrity-key: myundefined.myproject.RytlockBrimstone.4jiIheuih238hf83BYBfbiuyNWePJwt
    # 默认过期时间 long类型，毫秒单位
  #    default-expir-time: 172800
  # 上传文件路径
  file:
    upload-dir: ./static/file/
    show-mapping:
#      dns: 124.221.243.242
      dns: localhost
      port: 8989
      mapping: /static/file/